### ISSUE TITLE
GitHub API errors

### ISSUE THREAD

**Issue by salvafern** [EMODnet/seadog#10]
Hi @maelle

Thank you for this new package! Looks promising!

I have been trying it out and I'd like to document the issues I have ran into as probably other users will find similar difficulties.

First there was a problem with my GitHub credentials:

``` r
remotes::install_github("maelle/seadog")
#> Using github PAT from envvar GITHUB_PAT
#> Error: Failed to install 'seadog' from GitHub:
#>   HTTP error 401.
#>   Bad credentials
#> 
#>   Rate limit remaining: 56/60
#>   Rate limit reset at: 2022-02-23 15:41:45 UTC
#> 
#> 

seadog::advise_author()
#> Error in libgit2::git_repository_open_ext: could not find repository from 'C:\Users\salvadorf\AppData\Local\Temp\RtmpcLqHKp\reprex-4fd065093b5c-petit-dore'

seadog::advise_reviewer()
#> Error in libgit2::git_repository_open_ext: could not find repository from 'C:\Users\salvadorf\AppData\Local\Temp\RtmpcLqHKp\reprex-4fd065093b5c-petit-dore'
```

<sup>Created on 2022-02-23 by the [reprex package](https://reprex.tidyverse.org) (v2.0.0)</sup>

It was solved by providing the environment variable GITHUB_PAT with my newest GitHub key. I used quickly `Sys.setenv(GITHUB_PAT = "mykey")` but it's better to use an `.Renviron` file.

Then I ran `seadog::advise_author()`. There's a problem with the URL. I think it is due to the double "//" in the URL. I checked this in my browser and works fine with a single "/", while the double "//" throws a 404 error.

```r
seadog::advise_author()
#> Error in gh_process_response(raw) : 
#>   GitHub API error (404): 
#>   Message: Not Found
#> Read more at https://docs.github.com/rest
#> 
#> URL not found: https://api.github.com/repos//EMODnet/EMODnet-Biology-Project-Template-cookiecutter/issues
#> Type .Last.error.trace to see where the error occurred
```

Hope the feedback helps!

**Comment by maelle** [comment]
The feedback definitely helps!

For info what's recommended now is https://usethis.r-lib.org/articles/git-credentials.html#put-your-pat-into-the-local-git-credential-store (so, not in `.Renviron`) -- I've added a link to this article in the README.

**Comment by salvafern** [comment]
Thanks! I was not aware. Using gitcreds now.

**Comment by maelle** [comment]
Well, to be transparent I still had tokens in the wrong place myself :scream:

**Comment by maelle** [comment]
Also relevant https://blog.djnavarro.net/posts/2021-08-08_git-credential-helpers/
